### PR TITLE
Fixing source maps

### LINKED ISSUE #46: empty sourcemaps for esm bundle
the `.es6` assets that are generated with this plugin, have an empty sourcemap:

```.js
{"version":3,"sources":[],"names":[],"mappings":"","file":"esm/vendor-b2c1fb4206cbdb61d74d.es6.js","sourceRoot":""}
```
If you want I can make a test case webpack.config with `devtool: source-map` i

### PR DESCRIPTION
**Pull request by prateekbh**
- Fixes #46 
- Fixes propagating assets to parent compilation in right lifecycle hook

fyi @janicklas-ralph, @developit

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -148,32 +148,36 @@ class BabelEsmPlugin {
...
-              (chunkMap, chunk) => {
-                chunkMap[chunk.name] = chunk.files;
-                return chunkMap;
-              },
-              {},
-            );
-
-            compilation.chunks.forEach(chunk => {
-              const childChunkFiles = childChunkFileMap[chunk.name];
+            compilation.hooks.afterSeal.tapAsync(PLUGIN_NAME, seal => {
```
Comment (prateekbh) [inline src/index.js:151]: Without this the sourcemaps were generated twice under optimize lifecycle

**Comment by prateekbh** [comment]
Yes. Thats seems to be the case in my observation
